[package]
name = "mcscratchy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rs-sb3 = { path = "../rs-sb3" }
serde_json = "1.0.91"
